name: 🛠 Template Validate

on:
  pull_request:
    paths:
      - '**.go'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: 
          go-version: 1.19

      - name: Template Validation
        run: |
          go run . -ut
          go run . -validate
          go run . -validate -w workflows
        working-directory: v2/cmd/nuclei/